In [ ]:
import numpy as np 

#1) 0-29 arası(29 dahil, toplam 30 tam sayı) tam sayılardan oluşan bir boyutlu bir array oluşturun ardından bu array'in shape'ini (15,2) şeklinde güncelleyip 2 boyutlu hale getirin.


In [83]:
arr=np.arange(30).reshape(15,2)
arr

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

#2) 60 adet rastgele tam sayı verilerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'i istediğiniz shapelerde 3 boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.


In [93]:
arr=np.random.randint(10,100,60).reshape(3,5,4)
arr

array([[[81, 98, 12, 86],
        [65, 92, 24, 43],
        [77, 88, 26, 12],
        [43, 83, 45, 31],
        [83, 57, 91, 62]],

       [[26, 65, 88, 96],
        [91, 59, 91, 28],
        [60, 40, 50, 69],
        [36, 13, 86, 41],
        [89, 37, 69, 69]],

       [[63, 82, 81, 29],
        [77, 29, 87, 38],
        [86, 45, 67, 98],
        [23, 97, 22, 35],
        [88, 74, 85, 79]]])

In [92]:
arr.shape

(3, 5, 4)

In [91]:
arr.ndim

3

#3) 20 elemanlı ve sadece rakamlardan oluşan iki boyutlu bir array oluşturun. Ardından bu array'i düzleştirin ve tek boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.


In [109]:
arr=np.arange(20).reshape(4,5)
arr.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

#4) İstediğiniz herhangi elemanlardan oluşan 2 Boyutlu bir array oluşturun. Oluşturduğunuz bu 2 boyutlu array'in içindeki bütün elemanları hem yavaş yol olan for döngüsüyle hem de daha hızlı yol olan uygun NumPy metoduyla tek tek dönerek ekrana yazdırın.


In [126]:
arr=np.arange(20).reshape(10,2)
for x in arr:
  for y in x :
    print(y)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [132]:
for x in np.nditer(arr):
  print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


#5) 5,10,15,20,25,30 değerlerinden oluşan bir boyutlu bir array ve 1,2,3,4,5,6 değerlerinden oluşan başka bir boyutlu bir array oluşturun. Bu arraylerinin elemanlarına kendi aralarında 4 işlem uygulayın. İki arrayinde 1.indexindekiler toplansın/çıkartılsın/çarpılsın/bölünsün gibi.

In [138]:
arr1=np.array([5,10,15,20,25,30])
arr2=np.array([1,2,3,4,5,6])
print(arr1*arr2)
print("\n")
print(arr1/arr2)
print("\n")
print(arr1+arr2)
print("\n")
print(arr1-arr2)

[  5  20  45  80 125 180]


[5. 5. 5. 5. 5. 5.]


[ 6 12 18 24 30 36]


[ 4  8 12 16 20 24]


#6) 0-100 arası rastgele 10 tam sayıdan oluşan bir array oluşturun ve oluşturulan arrayin sum/mean/max/var/std değerlerini inceleyin.


In [148]:
arr=np.random.randint(0,100,10)
print(arr.mean())
print("\n\n")
print(arr.max())
print("\n\n")
print(arr.sum())
print("\n\n")
print(arr.var())
print("\n\n")
print(arr.std())

50.3



92



503



850.8100000000001



29.168647551780662


#7) 0-20 arası(20 dahil değil) tam sayılardan oluşan ve 500-530(530 dahil) arası tam sayılardan oluşan 2 array oluşturun. Ardından bu iki array'i concatenate ederek ekrana yazdırın.


In [150]:
arr1=np.arange(20)
arr2=np.arange(500,530)
np.concatenate([arr1,arr2])

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 501, 502, 503, 504, 505,
       506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518,
       519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529])

#8) 15-50(50 dahil) arası tam sayılardan oluşan bir array oluşturun. Daha sonra 10-100 arası(100 dahil) tam sayılardan oluşan 2.bir array oluşturun. Bu 2 arrayi concatanate ederek 3.bir array oluşturun ve bu array'in 25.index ile 50.index'i(50 dahil) arasındaki değerlerini 888 yapın.


In [153]:
arr1=np.arange(20)
arr2=np.arange(500,530)
arr3=np.concatenate([arr1,arr2])
arr3[25:50]=888
arr3

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 501, 502, 503, 504, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888])

#9) 0-40(40 dahil değil) arası değerlerden oluşan (8,5) shape'inde 2 boyutlu bir array ve  320-360(360 dahil değil) değerlerinden oluşan (8,5) shape'inde 2 boyutlubaşka bir array oluşturun. Devamında bu iki array'i hem axis = 0'da hem de axis = 1'de concatenate ederek farkı karşılaştırın.


In [154]:
arr1=np.arange(40).reshape(8,5)
arr2=np.arange(320,360).reshape(8,5)
print(np.concatenate([arr1,arr2],axis=0))
print(np.concatenate([arr1,arr2],axis=1))


[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]
 [ 25  26  27  28  29]
 [ 30  31  32  33  34]
 [ 35  36  37  38  39]
 [320 321 322 323 324]
 [325 326 327 328 329]
 [330 331 332 333 334]
 [335 336 337 338 339]
 [340 341 342 343 344]
 [345 346 347 348 349]
 [350 351 352 353 354]
 [355 356 357 358 359]]
[[  0   1   2   3   4 320 321 322 323 324]
 [  5   6   7   8   9 325 326 327 328 329]
 [ 10  11  12  13  14 330 331 332 333 334]
 [ 15  16  17  18  19 335 336 337 338 339]
 [ 20  21  22  23  24 340 341 342 343 344]
 [ 25  26  27  28  29 345 346 347 348 349]
 [ 30  31  32  33  34 350 351 352 353 354]
 [ 35  36  37  38  39 355 356 357 358 359]]


#10) 9.Soruda oluşturduğunuz 2 array'i axis = 2'de concatenate etmeye çalışın. Ardından axis = 2'de stacklemeye(yığınlamaya) çalışın. İkisi arasındaki farkı karşılaştırın.


In [157]:
arr1=np.arange(40).reshape(8,5)
arr2=np.arange(320,360).reshape(8,5)
print(np.stack([arr1,arr2],axis=2))

[[[  0 320]
  [  1 321]
  [  2 322]
  [  3 323]
  [  4 324]]

 [[  5 325]
  [  6 326]
  [  7 327]
  [  8 328]
  [  9 329]]

 [[ 10 330]
  [ 11 331]
  [ 12 332]
  [ 13 333]
  [ 14 334]]

 [[ 15 335]
  [ 16 336]
  [ 17 337]
  [ 18 338]
  [ 19 339]]

 [[ 20 340]
  [ 21 341]
  [ 22 342]
  [ 23 343]
  [ 24 344]]

 [[ 25 345]
  [ 26 346]
  [ 27 347]
  [ 28 348]
  [ 29 349]]

 [[ 30 350]
  [ 31 351]
  [ 32 352]
  [ 33 353]
  [ 34 354]]

 [[ 35 355]
  [ 36 356]
  [ 37 357]
  [ 38 358]
  [ 39 359]]]


#11) [1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5] değerlerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'in içinde değeri 5'e eşit olan değerlerin indexleri bulun.


In [160]:
arr=np.array([1,20,25,4,4,5,4,4,1,6,9,12,1,5])
np.where(arr==5)

(array([ 5, 13]),)

#12) Yukarıda oluşturduğunuz array içinde değeri çift olan değerlerin indexlerini bulun.


In [161]:
arr=np.array([1,20,25,4,4,5,4,4,1,6,9,12,1,5])
np.where(arr%2==0)

(array([ 1,  3,  4,  6,  7,  9, 11]),)

#13) Yukarıda oluşturduğunuz array içinde değeri 4'den büyük olan değerlerin indexlerini bulun.


In [162]:
arr=np.array([1,20,25,4,4,5,4,4,1,6,9,12,1,5])
np.where(arr>4)

(array([ 1,  2,  5,  9, 10, 11, 13]),)

#14) Yukarıda oluşturduğunuz array içinde değeri 5'e tam bölünen değerlerin indexlerini bulun.


In [166]:
arr=np.array([1,20,25,4,4,5,4,4,1,6,9,12,1,5])
np.where(arr%5==0)

(array([ 1,  2,  5, 13]),)

#15) 85-100(100 dahil) arasından rastgele 1 tam sayı seçin


In [168]:
arr=np.random.randint(85,100)
np.random.choice(arr)

14

#16) İki basamaklı tam sayılar arasından rastgele sayılar seçerek (3,3) shape'inde bir array oluşturun.


In [170]:
arr=np.random.randint(10,100,size=(3,3))
arr

array([[77, 82, 94],
       [88, 79, 84],
       [87, 37, 81]])

#17) 35-60 arasındaki tam sayılardan bir array oluşturun, ardından bu array içinden rastgele 1 tam sayı seçin.


In [173]:
arr=np.arange(35,60)
arr

array([35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59])

In [175]:
np.random.choice(arr)

37

#18) Sadece [3, 8, 10, 53] değerlerinden oluşan (2,5) shape'inde 2 boyutlu bir array oluşturun.

In [179]:
arr=np.random.choice([3,8,10,53],size=(2,5))
arr

array([[ 8, 10,  8, 53, 53],
       [ 8,  3,  8,  8, 53]])